[general]
connection = "Data Source=C:\\Users\\OPaimon\\source\\repos\\PaimonTGBot\\PaimonTGBot\\mydb.db;Version=3;"
output = "Datebase.fs"
namespace = "PaimonTGBot.Datebase"
cli_mutable = true
[sqlhydra_query_integration]
provider_db_type_attributes = true
table_declarations = true
[readers]
reader_type = "System.Data.Common.DbDataReader"
[filters]
include = []
exclude = []
